apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: two-tier-app
  name: two-tier-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels: 
        app: two-tier-app
    spec:
      containers:
        - env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: admin
            - name: MYSQL_DB
              value: mydb
          image: vishalshekokar999749/two-tier-flask-app_backend:latest
          imagePullPolicy: Always
          name: two-tier-app-ctr
          ports:
            - containerPort: 5000
    
